import { jsPDF } from "jspdf";
import type { DriverPayStructure } from "@/types/database";

export type DriverSettlementPdfInput = {
  fleetName: string;
  driverName: string;
  driverEmail: string | null;
  loadId: string;
  origin: string;
  destination: string;
  rateCents: number;
  payStructure: DriverPayStructure;
  payPercentOfGross: number;
  payCpmCents: number;
  loadedMiles: number;
  deadheadMiles: number;
  payDeadhead: boolean;
  deadheadRateCpmCents: number | null;
  deadheadPayCents: number;
  loadedDriverPayCents: number;
  driverTotalPayCents: number;
};

function formatMoney(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(cents / 100);
}

export function generateDriverSettlementPdf(
  input: DriverSettlementPdfInput
): Buffer {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(26, 28, 30);
  doc.text("Driver settlement statement", margin, y);
  y += 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(input.fleetName, margin, y);
  y += 16;
  doc.text(`Driver: ${input.driverName}`, margin, y);
  y += 14;
  if (input.driverEmail) {
    doc.text(`Email: ${input.driverEmail}`, margin, y);
    y += 14;
  }
  doc.text(`Load ID: ${input.loadId}`, margin, y);
  y += 24;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageW - margin, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(26, 28, 30);
  doc.text("Lane", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`${input.origin} → ${input.destination}`, margin, y);
  y += 16;
  doc.text(`Linehaul gross: ${formatMoney(input.rateCents)}`, margin, y);
  y += 22;

  doc.setFont("helvetica", "bold");
  doc.text("Pay profile", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  const rateLine =
    input.payStructure === "percent_gross"
      ? `Percent of load gross: ${input.payPercentOfGross}%`
      : `Loaded-mile rate: ${formatMoney(input.payCpmCents)} / mi (CPM)`;
  doc.text(rateLine, margin, y);
  y += 14;
  doc.text(`Loaded miles: ${input.loadedMiles.toFixed(1)}`, margin, y);
  y += 18;

  doc.setFont("helvetica", "bold");
  doc.text("Deadhead", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.text(
    input.payDeadhead
      ? `Paid deadhead: yes · Miles: ${input.deadheadMiles.toFixed(1)} · Rate: ${
          input.deadheadRateCpmCents != null
            ? `${formatMoney(input.deadheadRateCpmCents)}/mi`
            : "—"
        }`
      : "Paid deadhead: no",
    margin,
    y
  );
  y += 18;

  doc.setFont("helvetica", "bold");
  doc.text("Payout", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.text(`Loaded / gross pay: ${formatMoney(input.loadedDriverPayCents)}`, margin, y);
  y += 14;
  doc.text(`Deadhead pay: ${formatMoney(input.deadheadPayCents)}`, margin, y);
  y += 18;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total driver pay: ${formatMoney(input.driverTotalPayCents)}`, margin, y);
  y += 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "Generated by NexusFreight. Verify miles and rates against your ELD and contract.",
    margin,
    y
  );

  const out = doc.output("arraybuffer");
  return Buffer.from(out);
}
