import { jsPDF } from "jspdf";
import type { ServiceFeeType } from "@/types/database";

export type DeliveredLoadForSettlement = {
  id: string;
  origin: string;
  destination: string;
  rate_cents: number;
  delivered_at: string | null;
};

export type GenerateSettlementInput = {
  organizationName: string;
  carrierName: string;
  carrierMc: string | null;
  weekStart: Date;
  weekEnd: Date;
  feePercent: number;
  serviceFeeType?: ServiceFeeType | null;
  /** Per delivered load when serviceFeeType is flat (cents). */
  feeFlatCents?: number | null;
  loads: DeliveredLoadForSettlement[];
};

function formatMoney(cents: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(cents / 100);
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

/**
 * Aggregates delivered loads for a carrier over a week, applies fee %, returns a PDF buffer.
 */
export function generateSettlementPdf(input: GenerateSettlementInput): Buffer {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(26, 28, 30);
  doc.text("Carrier Settlement Statement", margin, y);
  y += 28;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text(input.organizationName, margin, y);
  y += 16;
  doc.text(
    `Period: ${formatDate(input.weekStart)} – ${formatDate(input.weekEnd)}`,
    margin,
    y
  );
  y += 28;

  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageW - margin, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(26, 28, 30);
  doc.text("Carrier", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(input.carrierName, margin, y);
  y += 14;
  if (input.carrierMc) {
    doc.text(`MC: ${input.carrierMc}`, margin, y);
    y += 14;
  }
  y += 10;

  const grossCents = input.loads.reduce((s, l) => s + l.rate_cents, 0);
  const feeType = input.serviceFeeType ?? "percent";
  const flatEach = Math.max(0, Math.round(Number(input.feeFlatCents ?? 0)));
  const feeCents =
    feeType === "flat"
      ? input.loads.length * flatEach
      : Math.round((grossCents * input.feePercent) / 100);
  const netCents = grossCents - feeCents;

  doc.setFont("helvetica", "bold");
  doc.text("Summary", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.text(`Gross (delivered loads): ${formatMoney(grossCents)}`, margin, y);
  y += 14;
  doc.text(
    feeType === "flat"
      ? `Platform fee (${formatMoney(flatEach)} × ${input.loads.length} loads): ${formatMoney(feeCents)}`
      : `Platform fee (${input.feePercent}%): ${formatMoney(feeCents)}`,
    margin,
    y
  );
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.text(`Net settlement: ${formatMoney(netCents)}`, margin, y);
  y += 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Delivered loads", margin, y);
  y += 18;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  for (const load of input.loads) {
    if (y > doc.internal.pageSize.getHeight() - margin - 40) {
      doc.addPage();
      y = margin;
    }
    const line = `${load.origin} → ${load.destination}  |  ${formatMoney(load.rate_cents)}  |  ${load.delivered_at ?? "—"}`;
    doc.text(line, margin, y);
    y += 14;
  }

  y += 20;
  if (y > doc.internal.pageSize.getHeight() - margin - 24) {
    doc.addPage();
    y = margin;
  }
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This statement is generated by NexusFreight for internal settlement purposes.",
    margin,
    y
  );

  const out = doc.output("arraybuffer");
  return Buffer.from(out);
}

/**
 * Filters loads to status delivered and date range [weekStart, weekEnd].
 */
export function filterDeliveredLoadsForWeek(
  loads: Array<
    DeliveredLoadForSettlement & { status: string; delivered_at: string | null }
  >,
  weekStart: Date,
  weekEnd: Date
): DeliveredLoadForSettlement[] {
  const start = weekStart.getTime();
  const end = weekEnd.getTime();
  return loads
    .filter((l) => l.status === "delivered" && l.delivered_at)
    .filter((l) => {
      const t = new Date(l.delivered_at!).getTime();
      return t >= start && t <= end;
    })
    .map(({ id, origin, destination, rate_cents, delivered_at }) => ({
      id,
      origin,
      destination,
      rate_cents,
      delivered_at,
    }));
}
